### ISSUE TITLE
A participate in translating

### ISSUE THREAD

**Issue by aboali19** [abdnh/abdnh.github.io#2]
hi @abdnh, 
I want to communicate with you to update the Arabic translation to keep pace with the development in Anki. Also, I intend to participate in translating the missing translations part ( [FAQs](https://faqs.ankiweb.net), [Addons,](https://addon-docs.ankiweb.net/intro.html) or others ).

**Comment by abdnh** [comment]
Hi @aboali1hassona
Thank you for your interest in contributing!
I thought of actually translating the FAQs when I have the time. We can maintain a fork of https://github.com/ankitects/faqs under my GitHub account or yours if you like. We can also work on the add-on docs after that.
Regarding the manual, I'm currently working on translating [the recently added sections](https://github.com/ankitects/anki-manual/commit/83400a8552e006399498f6879fa69d1b16f459a3). You can work on translating the latest additions, as can be seen in [the commit log here,](https://github.com/ankitects/anki-manual/commits/main) and open pull requests on my fork at https://github.com/abdnh/anki-manual.
If you would like to contribute to the program translations at https://i18n.ankiweb.net/ar/, you can follow the instructions at https://translating.ankiweb.net/intro.html to get started.
